on:
  push:
    path-ignore:
      - "LICENSE"
      - "README.md"
    tags-ignore:
      - "v*.*"
  pull_request:
    path-ignore:
      - "LICENSE"
      - "README.md"
    tags-ignore:
      - "v*.*"
jobs:
  upload_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "auth"
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: "upload-file"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "./assets/sample.csv"
          destination: "test-action-translation-bucket"

      - name: "update"
        uses: ./
        with:
          access-token: ${{ steps.auth.outputs.access_token }}
          bucket-name: "test-action-translation-bucket"
          glossary-name: "test-glossary"
          glossary-file-name: "sample.csv"
          project-id: "emerald-spring-353813"
          source-language: "ja"
          target-language: "en"
